services:
    backend:
        container_name: foodfinder-backend
        image: mongo:latest
        restart: unless-stopped
        environment:
            DB_NAME: foodfinder
            MONGO_INITDB_DATABASE: foodfinder
        ports:
            - 27017:27017
        volumes:
            - ./.docker/foodfinder-backend/seed-mongodb.js:/docker-entrypoint-initdb.d/seed-mongodb.js
            - mongodb_data_container:/data/db

    application:
        container_name: foodfinder-application
        image: node:22-bookworm
        working_dir: /usr/src/next
        ports:
            - "3000:3000"
        volumes:
            - .:/usr/src/next
        depends_on:
            - backend
        tty: true
        command: "npm run dev"

    jest:
        container_name: foodfinder-jest
        image: node:22-alpine
        working_dir: /usr/src/next
        volumes:
            - .:/usr/src/next
        depends_on:
            - backend
            - application
        environment:
            - NODE_ENV=test
        tty: true
        command: "npm run testWatch"
    
volumes:
    mongodb_data_container:

