services:
  application:
    container_name: foodfinder-application
    image: node:22-bookworm
    working_dir: /usr/src/next
    ports:
      - "${CLIENT_PORT:-3000}:3000"
    volumes:
      - .:/usr/src/next
    tty: true
    environment:
      - MONGO_URI=${MONGO_URI}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}

